"use strict";
/*Documento que almacena las constantes utilizadas en el documento IndDB_init.js*/
/*Estas constantes son los valores iniciales del StoreHouse y apartir de los cuales se inicia la practica 8 */
const db_name = "Store";

const categorias = [
  {IdCategory: 0 ,titulo: "General", descripcion:"Productos"},
  {IdCategory: 1 ,titulo: "Comunicacion", descripcion:"Telefonos moviles, Fijos, radios de onda corta, radios de onda larga y todo tipo de equipos relacionados con la comunicacion."},
  {IdCategory: 2 ,titulo: "Imagen", descripcion:"Equipos fotograficos, grabacion de Video y todo tipo de equipos relacionados con la Imagen."},
  {IdCategory: 3 ,titulo: "VideoConsolas", descripcion:"Videoconsolas fijas o portatiles, mandos y complementos."}
];

const productos = [
  {sn:"0001Apple", 
  nombre: "Iphone X", 
  descripcion: "La ultima version de movil de la conocida marca de la manzana...",
  iva: 24,
  precio: 849.99,
  imagenes: "../imagenes/iphoneX.jpg",
  marca: "Apple",
  camara: "50Mpx",
  memoria: "120Gb",
  tProducto: "Movil"},

  {sn:"0001Samsumg", 
  nombre: "Galaxy S8", 
  descripcion: "El ultimo movil de la competencia de la manzana",
  iva: 24,
  precio: 799.99,
  imagenes: "../imagenes/gs8.jpg",
  marca: "Samsumg",
  camara: "50Mpx",
  memoria: "120Gb",
  tProducto: "Movil"},

  {sn:"0001Fuji", 
  nombre: "Fuji Reflex", 
  descripcion: "Una camara para profesionales de la fotografia",
  iva: 18,
  precio: 1045,
  imagenes: "../imagenes/fujifilm.jpg",
  marca: "FujiFilm",
  lente: "Digital",
  memoria: "36Gb",
  tProducto: "Camara"},

  {sn:"0001Cannon", 
  nombre: "Canon Reflex", 
  descripcion: "Camara Reflex para profesionales de la fotografia",
  iva: 18,
  precio: 1258,
  imagenes: "../imagenes/canon.jpg",
  marca: "Canon",
  lente: "Digital",
  memoria: "50Gb",
  tProducto: "Camara"}, 

  {sn:"0001Sony", 
  nombre: "Play Station 4 500Gb", 
  descripcion: "Video consola de ultima generacion para amantes de los videojuegos de poca duracion",
  iva: 24,
  precio: 298,
  imagenes: "../imagenes/ps4.jpg",
  marca: "Sony",
  numJugadores: "6 Jugadores",
  portatil: "No",
  tProducto: "VideoConsola"},

  {sn:"0001Nintendo", 
  nombre: "Nintendo 3DS 3D", 
  descripcion: "Video consola portatil para los que les gusta jugar en cualquier momento",
  iva: 24,
  precio: 94,
  imagenes: "../imagenes/3ds.jpg",
  marca: "Nintendo",
  numJugadores: "1 Jugador",
  portatil: "Si",
  tProducto: "VideoConsola"},
];

const coord = [
  {longitud: 1, latitud:1},
  {longitud: 2, latitud:2},
  {longitud: 3, latitud:3},
];

const users = [
  {IdUsuario: 1 ,nombre: "prueba", pass: "prueba"},
  {IdUsuario: 2 ,nombre: "Jaime", pass: "123456789"}
];

const shops = [
  {
    cif: "134568",
    nombre: "Moviles Benito",
    direccion: "Plaza Mayor Nº2, Chillon",
    telefono: "926202020",
    category: [{IdCategory: 0 ,titulo: "Un titulo", descripcion: "Una descripcion"},
              {IdCategory: 1 ,titulo: "Comunicacion", descripcion: "Telefonos moviles, Fijos, radios de onda corta, radios de onda larga y todo tipo de equipos relacionados con la comunicacion."}],
    stock: [{producto: {sn:"0001Apple", 
              nombre: "Iphone X", 
              descripcion: "La ultima version de movil de la conocida marca de la manzana...",
              iva: 24,
              precio: 849.99,
              imagenes: "../imagenes/iphoneX.jpg",
              marca: "Apple",
              camara: "50Mpx",
              memoria: "120Gb",
              tProducto: "Movil"}, cantidad: 10, IdCategory: 1},
            {producto:  {sn:"0001Samsumg", 
              nombre: "Galaxy S8", 
              descripcion: "El ultimo movil de la competencia de la manzana",
              iva: 24,
              precio: 799.99,
              imagenes: "../imagenes/gs8.jpg",
              marca: "Samsumg",
              camara: "50Mpx",
              memoria: "120Gb",
              tProducto: "Movil"}, cantidad: 10, IdCategory: 1}],
    coords:{longitud: 1, latitud: 1}
  },
  {
    cif: "134569",
    nombre: "Camaras Pancracio",
    direccion: "C/El Azogue Nº1, Almaden",
    telefono: "926212121",
    category: [{IdCategory: 0 ,titulo: "Un titulo", descripcion: "Una descripcion"},
               {IdCategory: 2 ,titulo: "Imagen", descripcion: "Equipos fotograficos, grabacion de Video y todo tipo de equipos relacionados con la Imagen."},],
    stock: [{producto: {sn:"0001Fuji", 
              nombre: "Fuji Reflex", 
              descripcion: "Una camara para profesionales de la fotografia",
              iva: 18,
              precio: 1045,
              imagenes: "../imagenes/fujifilm.jpg",
              marca: "FujiFilm",
              lente: "Digital",
              memoria: "36Gb",
              tProducto: "Camara"}, cantidad: 5, IdCategory: 2},
            {producto:  {sn:"0001Cannon", 
              nombre: "Canon Reflex", 
              descripcion: "Camara Reflex para profesionales de la fotografia",
              iva: 18,
              precio: 1258,
              imagenes: "../imagenes/canon.jpg",
              marca: "Canon",
              lente: "Digital",
              memoria: "50Gb",
              tProducto: "Camara"}, cantidad: 4, IdCategory: 2},
          ],
    coords:{longitud: 2, latitud: 2}
  },
  {
    cif: "789469",
    nombre: "Electro Barato",
    direccion: "C/Calatrava Nº86, Ciudad Real",
    telefono: "926245056",
    category: [{IdCategory: 0 ,titulo: "Un titulo", descripcion: "Una descripcion"},
                {IdCategory: 1 ,titulo: "Comunicacion", descripcion: "Telefonos moviles, Fijos, radios de onda corta, radios de onda larga y todo tipo de equipos relacionados con la comunicacion."},
                {IdCategory: 2 ,titulo: "Imagen", descripcion: "Equipos fotograficos, grabacion de Video y todo tipo de equipos relacionados con la Imagen."},
                {IdCategory: 3 ,titulo: "VideoConsolas", descripcion: "Videoconsolas fijas o portatiles, mandos y complementos."}],
    stock: [{producto: {sn:"0001Apple", 
              nombre: "Iphone X", 
              descripcion: "La ultima version de movil de la conocida marca de la manzana...",
              iva: 24,
              precio: 849.99,
              imagenes: "../imagenes/iphoneX.jpg",
              marca: "Apple",
              camara: "50Mpx",
              memoria: "120Gb",
              tProducto: "Movil"}, cantidad: 2, IdCategory: 1},
            {producto:  {sn:"0001Cannon", 
              nombre: "Canon Reflex", 
              descripcion: "Camara Reflex para profesionales de la fotografia",
              iva: 18,
              precio: 1258,
              imagenes: "../imagenes/canon.jpg",
              marca: "Canon",
              lente: "Digital",
              memoria: "50Gb",
              tProducto: "Camara"}, cantidad: 4, IdCategory: 2},
            {producto:  {sn:"0001Sony", 
              nombre: "Play Station 4 500Gb", 
              descripcion: "Video consola de ultima generacion para amantes de los videojuegos de poca duracion",
              iva: 24,
              precio: 298,
              imagenes: "../imagenes/ps4.jpg",
              marca: "Sony",
              numJugadores: "6 Jugadores",
              portatil: "No",
              tProducto: "VideoConsola"}, cantidad: 4, IdCategory: 3},
            {producto:  {sn:"0001Nintendo", 
              nombre: "Nintendo 3DS 3D", 
              descripcion: "Video consola portatil para los que les gusta jugar en cualquier momento",
              iva: 24,
              precio: 94,
              imagenes: "../imagenes/3ds.jpg",
              marca: "Nintendo",
              numJugadores: "1 Jugador",
              portatil: "Si",
              tProducto: "VideoConsola"}, cantidad: 4, IdCategory: 3}
          ],
    coords:{longitud: 2, latitud: 2}
}];


  var stock = [{producto: {sn:"0001Apple", 
                nombre: "Iphone X", 
                descripcion: "La ultima version de movil de la conocida marca de la manzana...",
                iva: 24,
                precio: 849.99,
                imagenes: "../imagenes/iphoneX.jpg",
                marca: "Apple",
                camara: "50Mpx",
                memoria: "120Gb",
                tProducto: "Movil"}, cantidad: 2, IdCategory: 1},
              {producto:  {sn:"0001Cannon", 
                nombre: "Canon Reflex", 
                descripcion: "Camara Reflex para profesionales de la fotografia",
                iva: 18,
                precio: 1258,
                imagenes: "../imagenes/canon.jpg",
                marca: "Canon",
                lente: "Digital",
                memoria: "50Gb",
                tProducto: "Camara"}, cantidad: 4, IdCategory: 2},
              {producto:  {sn:"0001Sony", 
                nombre: "Play Station 4 500Gb", 
                descripcion: "Video consola de ultima generacion para amantes de los videojuegos de poca duracion",
                iva: 24,
                precio: 298,
                imagenes: "../imagenes/ps4.jpg",
                marca: "Sony",
                numJugadores: "6 Jugadores",
                portatil: "No",
                tProducto: "VideoConsola"}, cantidad: 4, IdCategory: 3},
              {producto:  {sn:"0001Nintendo", 
                nombre: "Nintendo 3DS 3D", 
                descripcion: "Video consola portatil para los que les gusta jugar en cualquier momento",
                iva: 24,
                precio: 94,
                imagenes: "../imagenes/3ds.jpg",
                marca: "Nintendo",
                numJugadores: "1 Jugador",
                portatil: "Si",
                tProducto: "VideoConsola"}, cantidad: 4, IdCategory: 3}
];
